// Package devcontainerjson generates the .devcontainer/devcontainer.json
// file. The output is tab-indented, raw UTF-8 (no HTML escaping), and
// preserves key insertion order via the in-package orderedMap.
package devcontainerjson

import (
	"bytes"
	"encoding/json"
	"fmt"
	"maps"
	"slices"
	"strings"

	"github.com/sukekyo26/cocoon/internal/generate"
)

const header = "// Auto-generated by cocoon — do not edit directly.\n"

// Generate disables HTML escaping so shell snippets in initializeCommand
// (e.g. `&&` chains) survive as literals instead of being rewritten.
func Generate(ctx *generate.WorkspaceContext) (string, error) {
	cfg := buildConfig(ctx)
	var raw bytes.Buffer
	enc := json.NewEncoder(&raw)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(cfg); err != nil {
		return "", fmt.Errorf("devcontainerjson: marshal: %w", err)
	}
	var indented bytes.Buffer
	if err := json.Indent(&indented, bytes.TrimRight(raw.Bytes(), "\n"), "", "\t"); err != nil {
		return "", fmt.Errorf("devcontainerjson: indent: %w", err)
	}
	return header + indented.String() + "\n", nil
}

func buildConfig(ctx *generate.WorkspaceContext) *orderedMap {
	// Pre-resolve forwardPorts so its slot stays between workspaceFolder and
	// shutdownAction regardless of which source(s) supply ports. Leaves nil
	// (typed any) when both are empty so the key is elided rather than
	// emitted as `"forwardPorts": []`.
	basePorts := append([]int{}, ctx.DevcontainerForwardPorts()...)
	overrides := ctx.DevcontainerOverrides()
	var forwardPorts any
	if extra, ok := overrides["forwardPorts"]; ok {
		delete(overrides, "forwardPorts")
		if merged := mergeForwardPorts(basePorts, extra); len(merged) > 0 {
			forwardPorts = merged
		}
	} else if len(basePorts) > 0 {
		forwardPorts = basePorts
	}

	base := newOrderedMap()
	base.set("name", ctx.ServiceName())
	base.set("dockerComposeFile", []string{"docker-compose.yml"})
	base.set("service", ctx.ServiceName())
	if cmd := initializeCommand(ctx); cmd != "" {
		base.set("initializeCommand", cmd)
	}
	workspaceFolder := "/home/" + ctx.Username() + "/" + ctx.WS.Workspace.DirOrDefault()
	if ctx.WS.Workspace.MountRootOrDefault() == "." {
		// Match the compose working_dir so VS Code opens the same
		// directory `cocoon exec` lands in.
		workspaceFolder += "/" + ctx.ServiceName()
	}
	base.set("workspaceFolder", workspaceFolder)
	if forwardPorts != nil {
		base.set("forwardPorts", forwardPorts)
	}
	base.set("shutdownAction", "stopCompose")
	// Container PID 1 starts as root (docker-entrypoint.sh remaps UID/GID,
	// then drops privileges); remoteUser makes VS Code attach as the
	// unprivileged user. updateRemoteUserUID is pinned false so VS Code does
	// not run its own host-UID remap on top of the entrypoint's.
	base.set("remoteUser", ctx.Username())
	base.set("updateRemoteUserUID", false)

	customizations := newOrderedMap()
	vscode := newOrderedMap()
	vscode.set("extensions", []string{})
	customizations.set("vscode", vscode)
	base.set("customizations", customizations)

	if len(overrides) == 0 {
		return base
	}
	deepMerge(base, overrides)
	return base
}

// initializeCommand mkdirs the certs build context (so BuildKit can resolve
// additional_contexts) and touches each [home_files] entry with mode 0o600
// (so Docker does not auto-create them as directories). ${HOME:?…} paths are
// double-quoted to survive host $HOME containing spaces; `dirname --`
// defends against a home directory starting with `-`. Returns "" when
// neither feature is configured.
func initializeCommand(ctx *generate.WorkspaceContext) string {
	var cmds []string
	if ctx.CertificatesEnabled() {
		cmds = append(cmds, `mkdir -p "`+generate.CertsHostPath+`"`)
	}
	for _, rel := range ctx.HomeFilesEntries() {
		p := `"` + generate.HomeFilesHostPathPrefix + "/" + rel + `"`
		// umask 077 must wrap both mkdir and touch so the parent dir
		// (e.g. ~/.gemini for .gemini/oauth_creds.json) inherits 0700,
		// matching ensureHomeFiles in cli/gen. Otherwise the parent
		// would be 0755 (default umask) and a 0600 file would sit in
		// a world-readable dir.
		cmds = append(cmds, `(umask 077 && mkdir -p "$(dirname -- `+p+`)" && touch `+p+`)`)
	}
	return strings.Join(cmds, " && ")
}

// mergeForwardPorts unions the base list with override entries, preserving
// base order and deduplicating. Override entries may be ints or any other
// JSON-compatible scalar.
func mergeForwardPorts(base []int, extra any) []any {
	out := make([]any, 0, len(base))
	seen := make(map[any]struct{}, len(base))
	for _, p := range base {
		out = append(out, p)
		seen[p] = struct{}{}
	}
	list, ok := extra.([]any)
	if !ok {
		return out
	}
	for _, p := range list {
		key := normalizeKey(p)
		if _, dup := seen[key]; dup {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, p)
	}
	return out
}

// normalizeKey collapses int64/int variants so dedup catches `3000` vs
// `int64(3000)` mismatches that come from go-toml's numeric decoding.
func normalizeKey(v any) any {
	switch x := v.(type) {
	case int64:
		return int(x)
	case float64:
		if float64(int(x)) == x {
			return int(x)
		}
	}
	return v
}

// deepMerge folds override into base. Existing keys preserve their position;
// new keys are appended in sorted order so the output is deterministic across
// Go map iteration.
func deepMerge(base *orderedMap, override map[string]any) {
	keys := slices.Sorted(maps.Keys(override))
	for _, k := range keys {
		v := override[k]
		existing, has := base.get(k)
		if has {
			if subBase, ok := existing.(*orderedMap); ok {
				if subOver, ok := v.(map[string]any); ok {
					deepMerge(subBase, subOver)
					continue
				}
			}
		}
		base.set(k, v)
	}
}
