// Package schema implements the `wsd schema dump` subcommand.
package schema

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/invopop/jsonschema"

	"github.com/sukekyo26/cocoon/internal/config"
)

// portRangeMin / portRangeMax mirror config.portMin / config.portMax which
// are unexported. They bound the integer ports advertised in the JSON Schema
// for `[ports].forward` long-form entries; keep these in sync with the Go
// validator in internal/config/validate.go.
const (
	portRangeMin = 1
	portRangeMax = 65535
)

// Sentinels mapped at the binary boundary in cmd/wsd.
var (
	ErrUsage   = errors.New("schema: usage error")
	ErrFailure = errors.New("schema: failure")
)

// Generate returns the JSON Schema bytes for workspace.toml.
func Generate() ([]byte, error) {
	r := &jsonschema.Reflector{
		ExpandedStruct:            true,
		AllowAdditionalProperties: false,
		DoNotReference:            false,
		FieldNameTag:              "toml",
	}
	schema := r.Reflect(&config.Workspace{}) //nolint:exhaustruct // reflector only needs the type
	schema.Title = "workspace-docker workspace.toml"
	schema.Description = "Schema for workspace-docker workspace.toml. Generated by `wsd schema dump`."

	customizePortsSchema(schema)

	buf, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal schema: %w", err)
	}
	buf = append(buf, '\n')
	return buf, nil
}

// customizePortsSchema replaces the auto-generated PortsSpec.forward.items
// (which is `true` because Forward is []any) with a oneOf of:
//
//   - a docker-compose short-form string (validated by config.PortShortFormPattern)
//   - a $ref to PortMappingLong
//
// and registers PortMappingLong under $defs so editor tooling can offer
// completion and early validation for both shapes.
func customizePortsSchema(schema *jsonschema.Schema) {
	if schema.Definitions == nil {
		schema.Definitions = jsonschema.Definitions{}
	}
	schema.Definitions["PortMappingLong"] = portMappingLongSchema()

	portsSpec, ok := schema.Definitions["PortsSpec"]
	if !ok || portsSpec.Properties == nil {
		return
	}
	forward, ok := portsSpec.Properties.Get("forward")
	if !ok || forward == nil {
		return
	}
	forward.Items = &jsonschema.Schema{
		OneOf: []*jsonschema.Schema{
			{Type: "string", Pattern: config.PortShortFormPattern},
			{Ref: "#/$defs/PortMappingLong"},
		},
	}
}

func portMappingLongSchema() *jsonschema.Schema {
	portRange := func() *jsonschema.Schema {
		return &jsonschema.Schema{
			Type:    "integer",
			Minimum: json.Number(fmt.Sprintf("%d", portRangeMin)),
			Maximum: json.Number(fmt.Sprintf("%d", portRangeMax)),
		}
	}
	props := jsonschema.NewProperties()
	props.Set("target", portRange())
	props.Set("published", &jsonschema.Schema{
		OneOf: []*jsonschema.Schema{
			portRange(),
			{Type: "string"},
		},
	})
	props.Set("host_ip", &jsonschema.Schema{Type: "string"})
	props.Set("protocol", &jsonschema.Schema{Type: "string", Enum: []any{"tcp", "udp"}})
	props.Set("mode", &jsonschema.Schema{Type: "string", Enum: []any{"ingress", "host"}})

	return &jsonschema.Schema{
		Type:                 "object",
		Properties:           props,
		Required:             []string{"target"},
		AdditionalProperties: jsonschema.FalseSchema,
	}
}

func writeFile(path string, data []byte) error {
	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("%w: mkdir %s: %w", ErrFailure, dir, err)
		}
	}
	if err := os.WriteFile(path, data, 0o644); err != nil { //nolint:gosec // schema is a public read-only generated file
		return fmt.Errorf("%w: write %s: %w", ErrFailure, path, err)
	}
	return nil
}
