// Package envfile renders the .env file that docker compose loads alongside
// .devcontainer/docker-compose.yml. Every value derives from workspace.toml
// or the project directory name, so the generated .env is host-independent
// and safe to commit and share across a team. Host identity (UID/GID and the
// docker socket group) is resolved at container start by docker-entrypoint.sh,
// not baked into this file.
package envfile

import (
	"errors"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/sukekyo26/cocoon/internal/generate"
)

// ErrNilContext is returned when Generate is called with a nil context.
var ErrNilContext = errors.New("envfile: nil workspace context")

// Generate renders the .env content. Every key derives from workspace.toml
// or the project directory name; the result carries no host-specific value,
// so the file is safe to commit alongside the rest of .devcontainer/.
func Generate(ctx *generate.WorkspaceContext) (string, error) {
	if ctx == nil || ctx.WS == nil {
		return "", ErrNilContext
	}

	var b strings.Builder
	b.WriteString("# Environment variables for docker compose.\n")
	b.WriteString("# Auto-generated by cocoon — do not edit manually.\n")
	b.WriteString("# Host-independent: no UID/GID/docker-gid; safe to commit and share.\n")
	b.WriteString("# Regenerate with: cocoon gen\n\n")
	fmt.Fprintf(&b, "COMPOSE_PROJECT_NAME=%s\n", composeProjectName(ctx))
	fmt.Fprintf(&b, "CONTAINER_SERVICE_NAME=%s\n", ctx.WS.Container.ServiceName)
	fmt.Fprintf(&b, "USERNAME=%s\n", ctx.WS.Container.Username)
	fmt.Fprintf(&b, "IMAGE=%s\n", ctx.WS.Container.Image)
	fmt.Fprintf(&b, "IMAGE_VERSION=%s\n", ctx.WS.Container.ImageVersion)
	return b.String(), nil
}

// composeProjectName mirrors docker-compose's "cwd basename" default by
// using ProjectDir, folded to lowercase (compose requires lowercase).
// Exotic chars (whitespace, punctuation) are left alone — docker compose
// surfaces those itself rather than letting cocoon silently rewrite paths.
// Falls back to ServiceName so `.env` always parses.
func composeProjectName(ctx *generate.WorkspaceContext) string {
	if ctx.ProjectDir != "" {
		base := filepath.Base(ctx.ProjectDir)
		if base != "" && base != "." && base != "/" {
			return strings.ToLower(base)
		}
	}
	return ctx.WS.Container.ServiceName
}
