// Package envfile renders the .env file that docker compose loads alongside
// .devcontainer/docker-compose.yml. The compose template uses ${VAR}
// interpolation so that host-specific values (UID/GID/DOCKER_GID) and
// workspace-specific values (CONTAINER_SERVICE_NAME, IMAGE/IMAGE_VERSION,
// USERNAME) can be filled in at build/run time.
package envfile

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"

	"github.com/sukekyo26/cocoon/internal/dockersock"
	"github.com/sukekyo26/cocoon/internal/generate"
)

// dockerGIDFallback is the value baked into .env when no docker socket and no
// /etc/group entry name "docker" are found on the host running `cocoon gen`.
// It matches the conventional Debian/Ubuntu docker package's group id.
const dockerGIDFallback = 999

var (
	// ErrNilContext is returned when Generate is called with a nil context.
	ErrNilContext = errors.New("envfile: nil workspace context")
	// ErrStatUnavailable signals the FileInfo had no accessible *syscall.Stat_t
	// (non-Unix host or test fake); the detector falls back to /etc/group.
	ErrStatUnavailable = errors.New("envfile: stat_t unavailable")
	// ErrDockerGroupAbsent indicates no "docker" line in /etc/group.
	ErrDockerGroupAbsent = errors.New("envfile: docker group not found")
)

// Generate sources UID/GID from os.Getuid/Getgid and resolves DOCKER_GID
// via the docker socket, /etc/group, then dockerGIDFallback in that order
// so .env always parses even on a host with no docker installed yet.
func Generate(ctx *generate.WorkspaceContext) (string, error) {
	if ctx == nil || ctx.WS == nil {
		return "", ErrNilContext
	}
	uid := os.Getuid()
	gid := os.Getgid()
	dockerGID := detectDockerGID()

	var b strings.Builder
	b.WriteString("# Environment variables for docker compose.\n")
	b.WriteString("# Auto-generated by cocoon — do not edit manually.\n")
	b.WriteString("# Regenerate with: cocoon gen\n\n")
	fmt.Fprintf(&b, "COMPOSE_PROJECT_NAME=%s\n", composeProjectName(ctx))
	fmt.Fprintf(&b, "CONTAINER_SERVICE_NAME=%s\n", ctx.WS.Container.ServiceName)
	fmt.Fprintf(&b, "USERNAME=%s\n", ctx.WS.Container.Username)
	fmt.Fprintf(&b, "UID=%d\n", uid)
	fmt.Fprintf(&b, "GID=%d\n", gid)
	fmt.Fprintf(&b, "DOCKER_GID=%d\n", dockerGID)
	fmt.Fprintf(&b, "IMAGE=%s\n", ctx.WS.Container.Image)
	fmt.Fprintf(&b, "IMAGE_VERSION=%s\n", ctx.WS.Container.ImageVersion)
	return b.String(), nil
}

// composeProjectName mirrors docker-compose's "cwd basename" default by
// using ProjectDir, folded to lowercase (compose requires lowercase).
// Exotic chars (whitespace, punctuation) are left alone — docker compose
// surfaces those itself rather than letting cocoon silently rewrite paths.
// Falls back to ServiceName so `.env` always parses.
func composeProjectName(ctx *generate.WorkspaceContext) string {
	if ctx.ProjectDir != "" {
		base := filepath.Base(ctx.ProjectDir)
		if base != "" && base != "." && base != "/" {
			return strings.ToLower(base)
		}
	}
	return ctx.WS.Container.ServiceName
}

// detectDockerGID stat'ing the live socket is the most accurate signal,
// /etc/group's "docker" line is the fallback, and dockerGIDFallback keeps
// .env parseable when both fail.
func detectDockerGID() int {
	for _, p := range dockersock.CandidatePaths() {
		if gid, err := socketFileGID(p); err == nil {
			return gid
		}
	}
	if gid, err := dockerGroupGIDFromFile("/etc/group"); err == nil {
		return gid
	}
	return dockerGIDFallback
}

func socketFileGID(path string) (int, error) {
	info, err := os.Stat(path) //nolint:gosec // path is from dockersock.CandidatePaths().
	if err != nil {
		return 0, fmt.Errorf("stat %s: %w", path, err)
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		return 0, ErrStatUnavailable
	}
	return int(stat.Gid), nil
}

func dockerGroupGIDFromFile(path string) (int, error) {
	f, err := os.Open(path) //nolint:gosec // path is /etc/group.
	if err != nil {
		return 0, fmt.Errorf("open %s: %w", path, err)
	}
	defer func() { _ = f.Close() }()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		parts := strings.SplitN(sc.Text(), ":", 4)
		if len(parts) >= 3 && parts[0] == "docker" {
			gid, atoiErr := strconv.Atoi(parts[2])
			if atoiErr != nil {
				return 0, fmt.Errorf("parse docker gid %q: %w", parts[2], atoiErr)
			}
			return gid, nil
		}
	}
	if scanErr := sc.Err(); scanErr != nil {
		return 0, fmt.Errorf("scan %s: %w", path, scanErr)
	}
	return 0, fmt.Errorf("%w in %s", ErrDockerGroupAbsent, path)
}
