// Package envfile renders the .env file that docker compose loads alongside
// .devcontainer/docker-compose.yml. The compose template uses ${VAR}
// interpolation so that host-specific values (UID/GID/DOCKER_GID) and
// workspace-specific values (CONTAINER_SERVICE_NAME, OS_IMAGE/OS_VERSION,
// USERNAME) can be filled in at build/run time.
package envfile

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
	"syscall"

	"github.com/sukekyo26/cocoon/internal/dockersock"
	"github.com/sukekyo26/cocoon/internal/generate"
)

// dockerGIDFallback is the value baked into .env when no docker socket and no
// /etc/group entry name "docker" are found on the host running `cocoon gen`.
// It matches the conventional Debian/Ubuntu docker package's group id.
const dockerGIDFallback = 999

// Sentinel errors for callers that want to distinguish failure modes; the
// linter (err113) requires these to be static rather than created inline.
var (
	// ErrNilContext is returned when Generate is called with a nil context.
	ErrNilContext = errors.New("envfile: nil workspace context")
	// ErrStatUnavailable is returned when os.Stat returns a FileInfo whose
	// underlying *syscall.Stat_t is not accessible (non-Unix host or test
	// fake). The detector falls back to /etc/group in that case.
	ErrStatUnavailable = errors.New("envfile: stat_t unavailable")
	// ErrDockerGroupAbsent is returned by dockerGroupGIDFromFile when no
	// "docker" line is present in /etc/group.
	ErrDockerGroupAbsent = errors.New("envfile: docker group not found")
)

// Generate returns the .env body for the given workspace context. UID/GID
// come from os.Getuid/Getgid; DOCKER_GID is detected from the docker socket
// or /etc/group, falling back to dockerGIDFallback when both are absent
// (e.g. cocoon gen running on a host with no docker installed yet).
func Generate(ctx *generate.WorkspaceContext) (string, error) {
	if ctx == nil || ctx.WS == nil {
		return "", ErrNilContext
	}
	uid := os.Getuid()
	gid := os.Getgid()
	dockerGID := detectDockerGID()

	var b strings.Builder
	b.WriteString("# Environment variables for docker compose.\n")
	b.WriteString("# Auto-generated by cocoon — do not edit manually.\n")
	b.WriteString("# Regenerate with: cocoon gen\n\n")
	fmt.Fprintf(&b, "COMPOSE_PROJECT_NAME=%s\n", ctx.WS.Container.ServiceName)
	fmt.Fprintf(&b, "CONTAINER_SERVICE_NAME=%s\n", ctx.WS.Container.ServiceName)
	fmt.Fprintf(&b, "USERNAME=%s\n", ctx.WS.Container.Username)
	fmt.Fprintf(&b, "UID=%d\n", uid)
	fmt.Fprintf(&b, "GID=%d\n", gid)
	fmt.Fprintf(&b, "DOCKER_GID=%d\n", dockerGID)
	fmt.Fprintf(&b, "OS_IMAGE=%s\n", ctx.WS.Container.Os)
	fmt.Fprintf(&b, "OS_VERSION=%s\n", ctx.WS.Container.OsVersion)
	return b.String(), nil
}

// detectDockerGID resolves the docker GID by stat'ing the live socket first
// (the most accurate signal) and falling back to /etc/group's "docker" line.
// Returns dockerGIDFallback when both fail so .env always parses.
func detectDockerGID() int {
	for _, p := range dockersock.CandidatePaths() {
		if gid, err := socketFileGID(p); err == nil {
			return gid
		}
	}
	if gid, err := dockerGroupGIDFromFile("/etc/group"); err == nil {
		return gid
	}
	return dockerGIDFallback
}

func socketFileGID(path string) (int, error) {
	info, err := os.Stat(path) //nolint:gosec // path is from dockersock.CandidatePaths().
	if err != nil {
		return 0, fmt.Errorf("stat %s: %w", path, err)
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		return 0, ErrStatUnavailable
	}
	return int(stat.Gid), nil
}

func dockerGroupGIDFromFile(path string) (int, error) {
	f, err := os.Open(path) //nolint:gosec // path is /etc/group.
	if err != nil {
		return 0, fmt.Errorf("open %s: %w", path, err)
	}
	defer func() { _ = f.Close() }()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		parts := strings.SplitN(sc.Text(), ":", 4)
		if len(parts) >= 3 && parts[0] == "docker" {
			gid, atoiErr := strconv.Atoi(parts[2])
			if atoiErr != nil {
				return 0, fmt.Errorf("parse docker gid %q: %w", parts[2], atoiErr)
			}
			return gid, nil
		}
	}
	if scanErr := sc.Err(); scanErr != nil {
		return 0, fmt.Errorf("scan %s: %w", path, scanErr)
	}
	return 0, fmt.Errorf("%w in %s", ErrDockerGroupAbsent, path)
}
