// Package lockfile owns cocoon.lock: the on-disk record of each
// version_capable plugin's resolved version and per-arch SHA256 checksums.
// `cocoon lock` writes it after network resolution; `cocoon gen` reads it
// offline so a generated workspace is reproducible. The file is wholly
// cocoon-owned (never hand-edited), so it is marshalled as a whole rather
// than line-mutated like the config file.
package lockfile

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/pelletier/go-toml/v2"

	"github.com/sukekyo26/cocoon/internal/config"
	"github.com/sukekyo26/cocoon/internal/fsx"
)

const (
	// FileName is the default lock file basename, written at the workspace
	// root alongside the discovered config file when [lockfile].name is unset. It aliases
	// config.DefaultLockFileName (the schema accessor's source of truth) so
	// the two never drift.
	FileName = config.DefaultLockFileName
	// Version is the current lock-format version. A lock with a newer
	// Version is rejected so an older cocoon does not silently misread it.
	Version = 1

	header = "# cocoon.lock — generated by `cocoon lock`; do not edit by hand.\n" +
		"# Records resolved plugin versions + per-arch checksums for reproducible builds.\n\n"
)

var rxSha256 = regexp.MustCompile(`^[a-f0-9]{64}$`)

// Lock errors (exported, errors.Is-matchable).
var (
	// ErrUnsupportedVersion is returned by Load when the file's lock_version
	// is newer than this cocoon understands.
	ErrUnsupportedVersion = errors.New("lockfile: unsupported lock_version (upgrade cocoon)")
	// ErrBadChecksum is returned by Load when a recorded checksum is not 64
	// lowercase hex chars.
	ErrBadChecksum = errors.New("lockfile: checksum is not 64 lowercase hex chars")
	// ErrEmptyVersion is returned by Load when a plugin entry has no version.
	ErrEmptyVersion = errors.New("lockfile: plugin entry has an empty version")
	// ErrMissingVersion is returned by Load when the file has no lock_version
	// (decoded as 0): a malformed or foreign lock that must be regenerated.
	ErrMissingVersion = errors.New("lockfile: missing lock_version (regenerate with `cocoon lock`)")
	// ErrDuplicatePlugin is returned by Load when two entries share a plugin
	// id, which would make Find's first-match overlay ambiguous.
	ErrDuplicatePlugin = errors.New("lockfile: duplicate plugin id")
)

// Lock is the parsed cocoon.lock. Plugins is kept sorted by ID so the
// marshalled output is byte-stable across runs.
type Lock struct {
	LockVersion int          `toml:"lock_version"`
	InputsHash  string       `toml:"inputs_hash"`
	Plugins     []LockPlugin `toml:"plugins,omitempty"`
}

// LockPlugin is one plugin's resolved entry. Requested is the workspace
// constraint that produced it ("latest" or "=1.2.3"); Version is the
// concrete resolved version. Checksums are empty for pgp / installer-only
// plugins. Extra carries frozen subcomponent selectors (android-sdk).
type LockPlugin struct {
	ID            string            `toml:"id"`
	Requested     string            `toml:"requested"`
	Version       string            `toml:"version"`
	ChecksumAMD64 string            `toml:"checksum_amd64,omitempty"`
	ChecksumARM64 string            `toml:"checksum_arm64,omitempty"`
	Extra         map[string]string `toml:"extra,omitempty"`
}

// Find returns the entry for id, or (zero, false) when absent.
func (l *Lock) Find(id string) (LockPlugin, bool) {
	if l == nil {
		return LockPlugin{}, false //nolint:exhaustruct // not-found sentinel
	}
	for _, p := range l.Plugins {
		if p.ID == id {
			return p, true
		}
	}
	return LockPlugin{}, false //nolint:exhaustruct // not-found sentinel
}

// Load reads and validates cocoon.lock at path. A missing file is reported
// via fs.ErrNotExist (callers treat that as "no lock") rather than a parse
// error; all other failures are returned.
func Load(path string) (*Lock, error) {
	data, err := os.ReadFile(path) //nolint:gosec // path provided by trusted caller
	if err != nil {
		return nil, config.WrapIO(path, err) //nolint:wrapcheck // WrapIO is the shared path-wrapping helper.
	}
	var l Lock
	if err := config.StrictUnmarshal(path, data, &l); err != nil {
		return nil, err //nolint:wrapcheck // StrictUnmarshal already returns a *ValidationError.
	}
	if err := l.validate(); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &l, nil
}

func (l *Lock) validate() error {
	switch {
	case l.LockVersion < 1:
		return ErrMissingVersion
	case l.LockVersion > Version:
		return fmt.Errorf("%w: file is v%d, this cocoon understands v%d", ErrUnsupportedVersion, l.LockVersion, Version)
	}
	seen := make(map[string]struct{}, len(l.Plugins))
	for _, p := range l.Plugins {
		if _, dup := seen[p.ID]; dup {
			return fmt.Errorf("plugin %q: %w", p.ID, ErrDuplicatePlugin)
		}
		seen[p.ID] = struct{}{}
		if p.Version == "" {
			return fmt.Errorf("plugin %q: %w", p.ID, ErrEmptyVersion)
		}
		for _, cs := range []string{p.ChecksumAMD64, p.ChecksumARM64} {
			if cs != "" && !rxSha256.MatchString(cs) {
				return fmt.Errorf("plugin %q: %w", p.ID, ErrBadChecksum)
			}
		}
	}
	return nil
}

// Marshal renders the lock to its canonical on-disk bytes (a fixed header
// comment plus TOML). Plugins are sorted by ID so the output is stable.
func Marshal(l *Lock) ([]byte, error) {
	sorted := make([]LockPlugin, len(l.Plugins))
	copy(sorted, l.Plugins)
	slices.SortFunc(sorted, func(a, b LockPlugin) int { return strings.Compare(a.ID, b.ID) })
	body, err := toml.Marshal(&Lock{LockVersion: l.LockVersion, InputsHash: l.InputsHash, Plugins: sorted})
	if err != nil {
		return nil, fmt.Errorf("marshal lock: %w", err)
	}
	return append([]byte(header), body...), nil
}

// Save atomically writes the lock to path (0o644).
func Save(path string, l *Lock) error {
	data, err := Marshal(l)
	if err != nil {
		return err
	}
	if err := fsx.AtomicWriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// ComputeInputsHash returns a stable SHA256 over the enabled
// version_capable plugins' (id, requested-spec) pairs. `cocoon lock --check`
// recomputes it offline and compares it against the lock's recorded hash to
// detect a lock that no longer matches the config file (a plugin added/removed
// or a constraint changed).
func ComputeInputsHash(requestedByID map[string]string) string {
	ids := make([]string, 0, len(requestedByID))
	for id := range requestedByID {
		ids = append(ids, id)
	}
	slices.Sort(ids)
	var b strings.Builder
	for _, id := range ids {
		b.WriteString(id)
		b.WriteByte('\x00')
		b.WriteString(requestedByID[id])
		b.WriteByte('\n')
	}
	sum := sha256.Sum256([]byte(b.String()))
	return hex.EncodeToString(sum[:])
}

// IsNotExist reports whether err is the "no lock file" condition.
func IsNotExist(err error) bool {
	return errors.Is(err, fs.ErrNotExist)
}

// PathFor returns the lock file path for ws: the configured (or default)
// basename joined to wsPath's directory. Both `cocoon lock` and `cocoon gen`
// call it so the write and read paths resolve identically. ws must be the
// parsed workspace (callers always have one by this point); NameOrDefault is
// nil-safe on a missing [lockfile] section.
func PathFor(wsPath string, ws *config.Workspace) string {
	return filepath.Join(filepath.Dir(wsPath), ws.Lockfile.NameOrDefault())
}
