//nolint:dupl // each catalog file shares the same boilerplate by design.
package i18n

func init() {
	register(LangEN, messagesEN_init)
	register(LangJA, messagesJA_init)
}

// messagesEN_init holds prompt / status strings emitted by `cocoon init`
// and `cocoon gen`. Keys are deliberately scoped with `init_` / `gen_`
// prefixes so they do not collide with the legacy `setup_*` table.
//
//nolint:gochecknoglobals,revive // catalog tables are file-scoped by design.
var messagesEN_init = map[string]string{
	// init prompts
	"init_prompt_service_name":          "Service name",
	"init_desc_service_name":            "Compose service name (e.g. \"my-api\").",
	"init_err_service_name_fmt":         "must start with a lowercase letter; only lowercase letters, digits, _ and - allowed",
	"init_prompt_username":              "Username",
	"init_desc_username":                "In-container user account (e.g. \"dev\").",
	"init_err_username_fmt":             "must start with a lowercase letter or _; only lowercase letters, digits, _ and - allowed",
	"init_err_required":                 "required — please enter a value",
	"init_prompt_image":                 "Base image",
	"init_desc_image":                   "Container base image. Pick ubuntu/debian for plain Linux, or a language-runtime image (node, python, go, rust, deno) to skip an apt install step. Note: picking go or rust here disables the matching cocoon plugin (no double-install).",
	"init_prompt_image_version":         "%s version",
	"init_desc_image_version":           "Pulled as FROM %s:<version> in the generated Dockerfile.",
	"init_prompt_image_version_static":  "Image version",
	"init_desc_image_version_static":    "Pulled as FROM <image>:<version> in the generated Dockerfile. Pick a suggestion or choose \"Other (manual input)\" to type any tag the upstream registry publishes.",
	"init_option_image_version_other":   "Other (manual input)",
	"init_prompt_image_version_other":   "Image version (manual)",
	"init_desc_image_version_other":     "Type the exact tag — e.g. 1.26.3-bookworm. Allowed: letters, digits, dot, underscore, hyphen.",
	"init_err_image_version_fmt":        "must be a plain Docker tag (letters, digits, dot, underscore, hyphen; no slash or colon)",
	"init_prompt_shell":                 "Login shell",
	"init_desc_shell":                   "Container login shell. bash is the cocoon default; zsh / fish drive shellrc generation differently.",
	"init_prompt_mount_root":            "Mount range",
	"init_desc_mount_root":              "How much of your filesystem should be visible inside the container?",
	"init_option_mount_cwd":             "Just this project (.)",
	"init_option_mount_parent":          "Parent directory — sibling repos visible (..)",
	"init_prompt_devcontainer":          "Generate .devcontainer/devcontainer.json for VS Code Dev Containers?",
	"init_desc_devcontainer":            "Says yes if you ever open this repo in VS Code Dev Containers; harmless otherwise.",
	"init_prompt_certificates":          "Bake user TLS certificates from ~/.cocoon/certs/ into the container image?",
	"init_desc_certificates":            "Enable when your build needs a corp CA inside the container (Zscaler, internal proxies, etc.). When off, no cert wiring lands in the generated artifacts.",
	"init_confirm_yes":                  "Yes",
	"init_confirm_no":                   "No",
	"init_prompt_apt":                   "Select common apt packages to install",
	"init_desc_apt":                     "Pre-checked categories are installed by default; uncheck what you do not need.",
	"init_prompt_plugins":               "Select plugins to enable",
	"init_desc_plugins":                 "Space toggles, Enter confirms. Pre-checked plugins are enabled by default.",
	"init_err_plugin_unknown_fmt":       "unknown plugin %q (run `cocoon plugin list` for the catalog)",
	"init_err_plugin_conflict_fmt":      "%s conflicts with %s — pick one",
	"init_err_plugin_load_fmt":          "load plugin catalog: %s",
	"init_prompt_alias_bundles":         "Select shell alias bundles",
	"init_desc_alias_bundles":           "Pre-canned alias sets merged into [container.shell].aliases. All start unchecked — opt in only what you want.",
	"init_err_alias_bundle_unknown_fmt": "unknown alias bundle %q",
	// workspace.toml inline comments (rendered into the generated file)
	"init_toml_header": "# workspace.toml — cocoon configuration (generated by `cocoon init`)\n# Edit freely; re-run `cocoon gen` to regenerate .devcontainer/.\n",
	"init_toml_section_workspace": "# [workspace] — generation-wide knobs.\n" +
		"#   mount_root: how much of your filesystem to expose. \".\" = cwd only, \"..\" = parent (siblings visible).\n" +
		"#   devcontainer: emit .devcontainer/devcontainer.json for VS Code Reopen-in-Container.",
	"init_toml_section_container": "# [container] — image identity.\n" +
		"#   service_name: docker-compose `services:` <key>. Used by `docker compose exec <name>`.\n" +
		"#   username / image / image_version: in-container account and FROM <image>:<image_version>.\n" +
		"#   image candidates: ubuntu, debian, node, python, go, rust, deno (deno resolves to denoland/deno).",
	"init_toml_section_container_shell": "# [container.shell] — login shell + per-shell rc injection.\n" +
		"#   default: bash | zsh | fish. The generator picks ~/.bashrc / ~/.zshrc / ~/.config/fish/config.fish.\n" +
		"#   aliases / env: appended to the rc file inside the image at build time.\n" +
		"#   bash & zsh use POSIX syntax (alias k='v', export K=V); fish translation is automatic.\n" +
		"#\n" +
		"# env example (uncomment + edit):\n" +
		"#   env = { EDITOR = \"vim\", PAGER = \"less -R\" }\n" +
		"# Caveats:\n" +
		"#   - EDITOR=vim / nano needs the `text-editors` apt category enabled.\n" +
		"#   - EDITOR=code only works when launched from VS Code Dev Containers (the `code` shim is\n" +
		"#     injected by VS Code, not by cocoon).\n" +
		"#   - PAGER=less / less -R needs the `utilities` apt category (less is not in cocoon's minimal base).",
	"init_toml_section_plugins": "# [plugins] — enable cocoon plugins (run `cocoon plugin list` for the catalog).\n" +
		"#   Pin versions in [plugins.versions] when you need reproducible builds.",
	"init_toml_section_plugins_versions": "# [plugins.versions] — pinned versions for the enabled plugins above.\n" +
		"#   Add checksum_amd64 / checksum_arm64 (64 lowercase hex chars) per block to verify install tarballs.",
	"init_toml_section_apt": "# [apt] — extra apt packages installed on top of cocoon's minimal base + selected categories.\n" +
		"#   Re-run `cocoon init --force` to change category checkboxes, or edit this list directly.",
	"init_toml_section_certificates": "# [certificates] — TLS certificate auto-bake from ~/.cocoon/certs/ on the host.\n" +
		"#   When enable = true the generators wire the host directory through to the build via\n" +
		"#   docker-compose's additional_contexts and the Dockerfile's RUN --mount=type=bind, so any\n" +
		"#   *.crt files placed there land in the container's trust store at build time. Default off.",
	// init result + next steps
	"init_wrote":             "wrote %s",
	"init_next_header":       "Next steps:",
	"init_next_step_gen":     "  1. cocoon gen",
	"init_next_step_compose": "  2. docker compose -f .devcontainer/docker-compose.yml up -d",
	"init_next_step_vscode":  `     (or open in VS Code → "Reopen in Container")`,
	// gen result + next steps
	"gen_wrote":               "wrote %s",
	"gen_next_header":         "To start the container:",
	"gen_next_step_compose":   "  docker compose -f .devcontainer/docker-compose.yml up -d",
	"gen_next_step_vscode":    `  (or open in VS Code → "Reopen in Container")`,
	"gen_certs_dir_created":   "created host directory %s (used as the cocoon_user_certs build context)",
	"gen_certs_notice_header": "Host TLS certificates:",
	"gen_certs_notice_path":   "  Drop *.crt files into ~/.cocoon/certs/ to bake corporate / private CAs into the container at build time.",
	"gen_certs_notice_team":   "  Team members who skip VS Code Dev Containers must run `mkdir -p ~/.cocoon/certs` once on their host (VS Code users get this auto-created via initializeCommand).",
}

// messagesJA_init mirrors messagesEN_init in Japanese. Untranslated keys
// (typically command-name examples like `cocoon gen`) intentionally keep
// the English form because the command name itself is not localized.
//
//nolint:gochecknoglobals,revive // catalog tables are file-scoped by design.
var messagesJA_init = map[string]string{
	// init prompts
	"init_prompt_service_name":          "サービス名",
	"init_desc_service_name":            "Compose のサービス名 (例: \"my-api\")。",
	"init_err_service_name_fmt":         "英小文字で始め、英小文字・数字・_・- のみ使用可です",
	"init_prompt_username":              "ユーザー名",
	"init_desc_username":                "コンテナ内ユーザーのアカウント名 (例: \"dev\")。",
	"init_err_username_fmt":             "英小文字または _ で始め、英小文字・数字・_・- のみ使用可です",
	"init_err_required":                 "必須項目です。値を入力してください",
	"init_prompt_image":                 "ベースイメージ",
	"init_desc_image":                   "コンテナのベースイメージ。Linux のみなら ubuntu/debian を、言語ランタイム入りなら node / python / go / rust / deno を選ぶと apt 1 ステップ省ける。go / rust を選んだ場合は同名の cocoon プラグインが無効化される（二重インストール回避）。",
	"init_prompt_image_version":         "%s のバージョン",
	"init_desc_image_version":           "生成される Dockerfile の FROM %s:<version> に展開されます。",
	"init_prompt_image_version_static":  "イメージのバージョン",
	"init_option_image_version_other":   "その他 (手動入力)",
	"init_prompt_image_version_other":   "イメージバージョン (手動)",
	"init_desc_image_version_other":     "正確なタグを入力してください (例: 1.26.3-bookworm)。許可文字: 英数字、ドット、アンダースコア、ハイフン。",
	"init_err_image_version_fmt":        "Docker タグの形式である必要があります (英数字 / ドット / アンダースコア / ハイフン。スラッシュやコロン禁止)",
	"init_desc_image_version_static":    "生成される Dockerfile の FROM <image>:<version> に展開されます。候補から選ぶか、「その他 (手動入力)」でレジストリ公開の任意タグを入力できます。",
	"init_prompt_shell":                 "ログインシェル",
	"init_desc_shell":                   "コンテナ内のログインシェル。bash が cocoon のデフォルト。zsh / fish は shellrc 生成が分岐します。",
	"init_prompt_mount_root":            "マウント範囲",
	"init_desc_mount_root":              "コンテナ内に見せるファイルシステムの範囲を選んでください。",
	"init_option_mount_cwd":             "このプロジェクトのみ (.)",
	"init_option_mount_parent":          "親ディレクトリ — 兄弟リポジトリも見える (..)",
	"init_prompt_devcontainer":          ".devcontainer/devcontainer.json を VS Code Dev Containers 用に生成しますか？",
	"init_desc_devcontainer":            "VS Code Dev Containers で開く可能性があれば Yes。そうでなくても害はありません。",
	"init_prompt_certificates":          "~/.cocoon/certs/ の TLS 証明書をコンテナイメージに取り込みますか？",
	"init_desc_certificates":            "Zscaler や社内プロキシなど、build 中に corp CA を信頼させる必要がある場合に Yes。off の場合は生成物に cert 関連の配線は一切乗りません。",
	"init_confirm_yes":                  "はい",
	"init_confirm_no":                   "いいえ",
	"init_prompt_apt":                   "インストールする apt パッケージのカテゴリを選択",
	"init_desc_apt":                     "プリチェック済みのカテゴリがデフォルトでインストールされます。不要なものはチェックを外してください。",
	"init_prompt_plugins":               "有効化するプラグインを選択",
	"init_desc_plugins":                 "スペースでトグル、Enter で確定します。プリチェック済みのプラグインがデフォルトで有効になります。",
	"init_err_plugin_unknown_fmt":       "未知のプラグイン %q (`cocoon plugin list` で一覧を確認してください)",
	"init_err_plugin_conflict_fmt":      "%s と %s は併用できません — どちらか一方を選んでください",
	"init_err_plugin_load_fmt":          "プラグインカタログの読み込みに失敗: %s",
	"init_prompt_alias_bundles":         "シェルエイリアスバンドルを選択",
	"init_desc_alias_bundles":           "プリセットの alias セットを [container.shell].aliases にマージします。初期チェックは全部 OFF — 欲しいものだけ選んでください。",
	"init_err_alias_bundle_unknown_fmt": "未知のエイリアスバンドル %q",
	// workspace.toml inline comments (rendered into the generated file)
	"init_toml_header": "# workspace.toml — cocoon 設定 (cocoon init で生成)\n# 自由に編集してください。cocoon gen で .devcontainer/ を再生成します。\n",
	"init_toml_section_workspace": "# [workspace] — 生成全体の挙動。\n" +
		"#   mount_root: コンテナへ見せるホスト範囲。\".\" = cwd のみ、\"..\" = 親ディレクトリ（兄弟リポも見える）。\n" +
		"#   devcontainer: VS Code Reopen-in-Container 用の devcontainer.json を生成するか。",
	"init_toml_section_container": "# [container] — イメージの素性。\n" +
		"#   service_name: docker-compose の `services:` <キー>。`docker compose exec <名前>` で使う。\n" +
		"#   username / image / image_version: コンテナ内ユーザー名と FROM <image>:<image_version>。\n" +
		"#   image 候補: ubuntu, debian, node, python, go, rust, deno (deno は denoland/deno に展開)。",
	"init_toml_section_container_shell": "# [container.shell] — ログインシェル + シェル別 rc 注入。\n" +
		"#   default: bash | zsh | fish。生成系が ~/.bashrc / ~/.zshrc / ~/.config/fish/config.fish を選ぶ。\n" +
		"#   aliases / env: イメージビルド時に rc ファイルへ追記される。\n" +
		"#   bash と zsh は POSIX 記法 (alias k='v', export K=V)、fish は自動翻訳。\n" +
		"#\n" +
		"# env の設定例（コメントアウトを外して編集）:\n" +
		"#   env = { EDITOR = \"vim\", PAGER = \"less -R\" }\n" +
		"# 注意:\n" +
		"#   - EDITOR=vim / nano は apt カテゴリ `text-editors` の有効化が前提。\n" +
		"#   - EDITOR=code は VS Code Dev Containers で開いたときのみ動く（`code` シムは\n" +
		"#     VS Code が注入するもので、cocoon は関与しない）。\n" +
		"#   - PAGER=less / less -R は apt カテゴリ `utilities` が前提（less は cocoon の最小ベースに含まれない）。",
	"init_toml_section_plugins": "# [plugins] — cocoon プラグインの有効化（一覧は `cocoon plugin list`）。\n" +
		"#   再現性が必要なら [plugins.versions] でバージョン固定。",
	"init_toml_section_plugins_versions": "# [plugins.versions] — 上で有効化したプラグインに対するバージョン固定。\n" +
		"#   各ブロックに checksum_amd64 / checksum_arm64（64 文字小文字 hex）を足すと install 時のハッシュ検証が有効になる。",
	"init_toml_section_certificates": "# [certificates] — ホスト側 ~/.cocoon/certs/ の TLS 証明書をコンテナイメージに自動取り込み (opt-in)。\n" +
		"#   enable = true のときジェネレータが docker-compose の additional_contexts と Dockerfile の\n" +
		"#   RUN --mount=type=bind を配線し、ホスト側 *.crt が build 時にトラストストアへマージされる。\n" +
		"#   デフォルト off。",
	"init_toml_section_apt": "# [apt] — cocoon の最小ベース + 選択カテゴリに追加する apt パッケージ。\n" +
		"#   カテゴリのチェックを変えるなら `cocoon init --force` を再実行、または直接このリストを編集。",
	// init result + next steps
	"init_wrote":             "%s を書き出しました",
	"init_next_header":       "次のステップ:",
	"init_next_step_gen":     "  1. cocoon gen",
	"init_next_step_compose": "  2. docker compose -f .devcontainer/docker-compose.yml up -d",
	"init_next_step_vscode":  `     (または VS Code で「Reopen in Container」を実行)`,
	// gen result + next steps
	"gen_wrote":               "%s を書き出しました",
	"gen_next_header":         "コンテナを起動するには:",
	"gen_next_step_compose":   "  docker compose -f .devcontainer/docker-compose.yml up -d",
	"gen_next_step_vscode":    `  (または VS Code で「Reopen in Container」を実行)`,
	"gen_certs_dir_created":   "ホスト側ディレクトリ %s を作成しました (cocoon_user_certs ビルドコンテキストとして使用)",
	"gen_certs_notice_header": "ホスト TLS 証明書:",
	"gen_certs_notice_path":   "  社内 / プライベート CA を取り込む場合は `.crt` を `~/.cocoon/certs/` に置いてください。build 時に自動取り込みされます。",
	"gen_certs_notice_team":   "  VS Code Dev Containers を使わないチームメンバーは初回のみホストで `mkdir -p ~/.cocoon/certs` の実行が必要です (VS Code 経由は initializeCommand で自動)。",
}
