// Package shellrc generates the per-shell rc fragment file consumed by the
// container's login shell:
//   - bash: config/.bashrc_custom.generated      (sourced from ~/.bashrc)
//   - zsh:  config/.zshrc_custom.generated       (sourced from ~/.zshrc)
//   - fish: config/config.fish_custom.generated  (sourced from ~/.config/fish/config.fish)
//
// Content is rendered using the chosen shell's syntax: bash and zsh share
// POSIX-style `export K=V` / `alias k='v'`; fish uses `set -gx K V` /
// `alias k 'v'`.
//
// The user-editable companion file is shell-agnostic and lives at
// config/shell_custom (same path regardless of [container.shell].default).
// Users put either POSIX or fish syntax in that file depending on their
// active shell — see config/shell_custom.example for both forms.
package shellrc

import (
	"fmt"
	"sort"

	"github.com/sukekyo26/cocoon/internal/generate"
	"github.com/sukekyo26/cocoon/internal/generate/shellx"
	"github.com/sukekyo26/cocoon/internal/generate/tmplx"
)

// UserRCRelPath is the workspace-relative path to the user-editable rc
// fragment. It is shell-agnostic — bash, zsh and fish all source the same
// file, so users only maintain one place for their custom aliases / env.
const UserRCRelPath = "config/shell_custom"

// HeaderFor returns the leading comment block for the given login shell. It
// always ends with a trailing newline so callers can append sections cleanly.
func HeaderFor(shell string) string {
	_ = shell // kept for API stability; header text is shell-agnostic now.
	return "# Auto-generated by setup-docker.sh from [container.shell] of workspace.toml.\n" +
		"# DO NOT EDIT — your changes will be overwritten on next run.\n" +
		"# For persistent custom shell config, edit " + UserRCRelPath + " instead.\n"
}

// RelPathFor returns the workspace-relative output path for the given login
// shell ("bash" | "zsh" | "fish"). Unknown shells fall back to bash.
func RelPathFor(shell string) string {
	switch shell {
	case "fish":
		return "config/config.fish_custom.generated"
	case "zsh":
		return "config/.zshrc_custom.generated"
	default:
		return "config/.bashrc_custom.generated"
	}
}

// KnownGeneratedRelPaths returns every generated rc-fragment path that this
// package may produce. Callers use it to remove stale files when the user
// switches [container.shell].default.
func KnownGeneratedRelPaths() []string {
	return []string{
		RelPathFor("bash"),
		RelPathFor("zsh"),
		RelPathFor("fish"),
	}
}

type section struct {
	Title string
	Lines []string
}

type templateData struct {
	Header   string
	Sections []section
}

var tmpl = tmplx.MustParse("shellrc", `{{ .Header }}{{ range .Sections }}
# {{ .Title }}{{ range .Lines }}
{{ . }}{{ end }}
{{ end }}`, nil)

// Generate returns the per-shell rc fragment for the given context. relPath
// is the workspace-relative output path; body is the file content. When
// [container.shell] is absent or empty only the header is returned.
func Generate(ctx *generate.WorkspaceContext) (relPath, body string, err error) {
	shell := "bash"
	syntax := "posix"
	var aliases, env map[string]string
	if ctx != nil {
		shell = ctx.LoginShell()
		syntax = ctx.RCSyntax()
		aliases = ctx.ShellAliases()
		env = ctx.ShellEnv()
	}

	rel := RelPathFor(shell)
	header := HeaderFor(shell)
	if len(aliases) == 0 && len(env) == 0 {
		return rel, header, nil
	}

	data := templateData{Header: header, Sections: nil}
	if len(env) > 0 {
		data.Sections = append(data.Sections, section{
			Title: "Environment variables",
			Lines: renderEnvLines(env, syntax),
		})
	}
	if len(aliases) > 0 {
		data.Sections = append(data.Sections, section{
			Title: "Aliases",
			Lines: renderAliasLines(aliases, syntax),
		})
	}

	out, err := tmplx.Render(tmpl, data)
	if err != nil {
		return rel, "", fmt.Errorf("shellrc: %w", err)
	}
	return rel, out, nil
}

func renderEnvLines(env map[string]string, syntax string) []string {
	keys := sortedKeys(env)
	out := make([]string, len(keys))
	for i, k := range keys {
		if syntax == "fish" {
			out[i] = "set -gx " + k + " " + shellx.FishQuote(env[k])
		} else {
			out[i] = "export " + k + "=" + shellx.ShellQuote(env[k])
		}
	}
	return out
}

func renderAliasLines(aliases map[string]string, syntax string) []string {
	keys := sortedKeys(aliases)
	out := make([]string, len(keys))
	for i, k := range keys {
		if syntax == "fish" {
			out[i] = "alias " + k + " " + shellx.FishQuote(aliases[k])
		} else {
			out[i] = "alias " + k + "=" + shellx.ShellQuote(aliases[k])
		}
	}
	return out
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
