#!/usr/bin/env bash
# ============================================================
# manage.sh — project-scoped Docker clean / rebuild helper
# ============================================================
# Generated by `cocoon gen`. Run this on the HOST (not inside the
# container) to clean up or rebuild the Docker resources for THIS
# project only. Scoping is automatic: `docker compose` labels every
# resource it creates with this project's name, so the commands below
# never touch unrelated projects — the one exception is `prune-cache`,
# which is global by nature (see its warning).
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"
ENV_FILE="${SCRIPT_DIR}/.env"

ASSUME_YES=0

usage() {
  cat <<'EOF'
manage.sh — project-scoped Docker clean / rebuild helper

Usage: ./manage.sh [-y] <command>

Commands:
  clean              Remove this project's containers, networks, volumes
                     and locally-built image (build cache is NOT touched).
  clean containers   Remove containers only; networks, volumes, image kept.
  clean image        Remove containers, networks and the locally-built
                     image; volumes (your data) are kept.
  clean volumes      Remove containers, networks and named volumes; the
                     locally-built image is kept (fast rebuild).
  rebuild            Rebuild the image with --no-cache and recreate the
                     container. Volumes are kept.
  exec <cmd...>      Run <cmd> in the running container as the remap target
                     user (--user from .env), e.g. exec zsh. Args pass through
                     verbatim, so flags like -la reach the container.
  prune-cache        Prune the GLOBAL Docker build cache. THIS AFFECTS
                     EVERY Docker project on this host, not just this one.

Options:
  -y, --yes          Skip the confirmation prompt.
  -h, --help         Show this help.
EOF
}

die() {
  echo "manage.sh: $*" >&2
  exit 1
}

# dc runs docker compose pinned to this project's generated files, so it
# stays scoped to this project regardless of the caller's directory.
dc() {
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

preflight() {
  command -v docker >/dev/null 2>&1 || die "docker not found on PATH"
  docker compose version >/dev/null 2>&1 ||
    die "'docker compose' is unavailable; install the Compose v2 plugin"
  [ -f "$COMPOSE_FILE" ] || die "not found: ${COMPOSE_FILE} (run 'cocoon gen' first)"
  [ -f "$ENV_FILE" ] || die "not found: ${ENV_FILE} (run 'cocoon gen' first)"
}

# require_buildx fails fast when the buildx plugin is missing. `rebuild`
# runs `docker compose build`, and the generated Dockerfile relies on
# BuildKit-only features (`# syntax=`, `RUN --mount=type=cache`, and
# additional build contexts). Without buildx, compose silently falls back
# to the legacy "classic" builder and the build fails with a confusing
# "classic builder doesn't support additional contexts" error.
require_buildx() {
  docker buildx version >/dev/null 2>&1 && return 0
  echo "manage.sh: docker buildx is not installed — 'rebuild' needs BuildKit." >&2
  echo "  The generated Dockerfile / compose file use BuildKit-only features," >&2
  echo "  which the legacy 'classic' builder cannot handle. Install buildx with:" >&2
  echo "    sudo apt-get install docker-buildx-plugin" >&2
  echo "  or place the binary from https://github.com/docker/buildx/releases" >&2
  echo "  into /usr/libexec/docker/cli-plugins/docker-buildx (chmod +x)." >&2
  exit 1
}

# env_value reads the first KEY=... value from the generated .env (a flat
# KEY=value file written by `cocoon gen` — no quoting/interpolation). Prints
# empty when the key is absent so callers decide how to handle it.
env_value() {
  grep -m1 -E "^$1=" "$ENV_FILE" | cut -d= -f2- || true
}

# project_name reads COMPOSE_PROJECT_NAME from .env for display only; the
# actual scoping is done by docker compose via -f/--env-file.
project_name() {
  local name
  name="$(env_value COMPOSE_PROJECT_NAME)"
  echo "${name:-unknown}"
}

confirm() {
  if [ "$ASSUME_YES" -eq 1 ]; then
    return 0
  fi
  if [ ! -t 0 ]; then
    die "no terminal for confirmation; re-run with -y to proceed"
  fi
  local reply
  printf '%s [y/N] ' "$1"
  read -r reply
  case "$reply" in
    y | Y | yes | YES) return 0 ;;
    *)
      echo "aborted."
      exit 0
      ;;
  esac
}

cmd_clean() {
  local target="$1"
  local proj
  proj="$(project_name)"
  case "$target" in
    "" | all)
      confirm "Remove containers, networks, volumes and the built image for '${proj}'?"
      dc down --volumes --rmi local --remove-orphans
      ;;
    containers)
      confirm "Remove containers for '${proj}'? (networks, volumes, image kept)"
      dc rm --stop --force
      ;;
    image | images)
      confirm "Remove containers, networks and the built image for '${proj}'? (volumes kept)"
      dc down --rmi local --remove-orphans
      ;;
    volumes)
      confirm "Remove containers, networks and named volumes for '${proj}'? (image kept)"
      dc down --volumes --remove-orphans
      ;;
    *)
      die "unknown clean target: ${target} (try: containers, image, volumes)"
      ;;
  esac
  echo "done."
}

cmd_rebuild() {
  local proj
  proj="$(project_name)"
  require_buildx
  confirm "Rebuild the image for '${proj}' with --no-cache and recreate the container?"
  dc build --no-cache
  dc up -d --force-recreate
  echo "done."
}

# cmd_exec runs a command in the already-running container as the remap target
# user. The container starts as root (USER root + setpriv drop in
# docker-entrypoint.sh), so a bare `docker compose exec` lands you as root with
# none of the user's shell environment; --user <USERNAME> restores the right
# identity. Service and user both come from the generated .env; the caller
# supplies the command explicitly, like `docker compose exec`.
cmd_exec() {
  [ "$#" -gt 0 ] || die "exec needs a command, e.g. ./manage.sh exec zsh"
  local user service
  user="$(env_value USERNAME)"
  service="$(env_value CONTAINER_SERVICE_NAME)"
  [ -n "$user" ] || die "USERNAME not set in ${ENV_FILE} (run 'cocoon gen' first)"
  [ -n "$service" ] || die "CONTAINER_SERVICE_NAME not set in ${ENV_FILE} (run 'cocoon gen' first)"
  dc exec --user "$user" "$service" "$@"
}

cmd_prune_cache() {
  echo "WARNING: this prunes the GLOBAL Docker build cache." >&2
  echo "         It affects every Docker project on this host, not just this one." >&2
  confirm "Prune the global Docker build cache?"
  docker builder prune -f
  echo "done."
}

main() {
  # `exec` forwards its entire command line to the container verbatim, so it
  # must bypass the option parser below (which would reject e.g. `-la`).
  if [ "${1:-}" = exec ]; then
    shift
    preflight
    cmd_exec "$@"
    return
  fi

  local args=()
  while [ "$#" -gt 0 ]; do
    case "$1" in
      -y | --yes) ASSUME_YES=1 ;;
      -h | --help)
        usage
        exit 0
        ;;
      -*) die "unknown option: $1 (try -h)" ;;
      *) args+=("$1") ;;
    esac
    shift
  done

  if [ "${#args[@]}" -eq 0 ]; then
    usage >&2
    exit 2
  fi

  preflight

  case "${args[0]}" in
    clean) cmd_clean "${args[1]:-}" ;;
    rebuild) cmd_rebuild ;;
    prune-cache) cmd_prune_cache ;;
    *)
      echo "manage.sh: unknown command: ${args[0]}" >&2
      usage >&2
      exit 2
      ;;
  esac
}

main "$@"
