package generate

// Password-sudo build-secret constants shared by the dockerfile / compose
// generators and the gen missing-secret warning. Centralized so the emit
// sites stay in lockstep (the secret id the Dockerfile mounts must match the
// name compose defines).

const (
	// SudoPasswordSecretName is the compose secret id and the Dockerfile
	// `RUN --mount=type=secret,id=…` id; the secret mounts at
	// /run/secrets/<name>.
	SudoPasswordSecretName = "sudo_password"

	// SudoPasswordSecretFile is the compose secret source file, resolved
	// relative to the compose project directory (.devcontainer/). It is
	// gitignored and never committed.
	//nolint:gosec // G101: a gitignored filename, not a hardcoded credential.
	SudoPasswordSecretFile = ".env.local"

	// SudoPasswordEnvKey is the key the Dockerfile parses out of the secret
	// file (an env-file): the line `SUDO_PASSWORD=<value>` supplies the
	// container user's sudo password.
	SudoPasswordEnvKey = "SUDO_PASSWORD"
)

// SudoPasswordGitignore is the body of the generated .devcontainer/.gitignore
// in password mode. It ignores ONLY the secret file — the generated .env is
// committable and intentionally not ignored. Shared by `cocoon gen` (artifact)
// and `cocoon init` (interactive seed) so both write identical content.
const SudoPasswordGitignore = "# Auto-generated by cocoon — do not edit manually.\n" +
	"# Local sudo password secret (build secret); host-local, never committed.\n" +
	SudoPasswordSecretFile + "\n"
